- AssetInformationApi/V1/Domain/Enums.cs
> Updated list of asset types

- AssetInformationApi/Startup.cs
- AssetInformationApi/serverless.yml
[Jira Ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-1419)
updating API to ensure that when an x-correlation-id is sent in the request
> add correlation header

- terraform/development/dynamodb.tf
- terraform/development/main.tf
- terraform/development/variables.tf
- terraform/production/dynamodb.tf
- terraform/production/main.tf
- terraform/production/variables.tf
- terraform/staging/dynamodb.tf
- terraform/staging/main.tf
- terraform/staging/variables.tf
https://hackney.atlassian.net/browse/MTTL-1461
Get metrics in easy to view dashboard
Added CW dashboard
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
Are there any next steps that need to addressed after merging this PR? Add them here.
> added CW dashboard

- .circleci/config.yml
> Add filters to circleci config

- terraform/development/dynamodb.tf
- terraform/production/dynamodb.tf
- terraform/staging/dynamodb.tf
> Update timeout to Terraform GSI

- .circleci/config.yml
- terraform/development/dynamodb.tf
- terraform/production/dynamodb.tf
- terraform/staging/dynamodb.tf
Are there any next steps that need to addressed after merging this PR? Add them here.
> Update DynamoDb timeouts block

- .circleci/config.yml
- .dockerignore
- AssetInformationApi.Tests/Dockerfile
- docker-compose.yml
- sonar-project.properties
https://hackney.atlassian.net/browse/MTTL-2192 
Sonar cloud Pipeline
> sonarcloud pipeline

- .circleci/config.yml
- terraform/development/terraform-compliance/dynamodb.feature
- terraform/production/terraform-compliance/dynamodb.feature
- terraform/staging/terraform-compliance/dynamodb.feature
[Jira Ticket](https://hackney.atlassian.net/browse/MTTL-2286)
Added TF Compliance rules
> Terraform Compliance rules

- .circleci/config.yml
- AssetInformationApi/serverless.yml
[JIRA ticket](https://hackney.atlassian.net/browse/MTTL-2364)
Removed deprecated --account flag
> Removed deprecated --account flag

- .circleci/config.yml
- AssetInformationApi/serverless.yml
[JIRA ticket](https://hackney.atlassian.net/browse/MTTL-2400)
Enabled AWS WAF
> Enabled AWS WAF

- AssetInformationApi/policies/require-authorizer.js
- AssetInformationApi/serverless.yml
[JIRA ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-2415)
> Enable serverless safeguards

- .circleci/config.yml
> Install plugin

- AssetInformationApi/policies/require-authorizer.js
> updated require-authorizer.js

- .circleci/config.yml
- AssetInformationApi.Tests/Dockerfile
https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?assignee=624c20c6a629c30068a81020&selectedIssue=MTTL-2956
Fix SonarCloud Issue
> SonarCloud Issue

- AssetInformationApi/AssetInformationApi.csproj
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
Are there any next steps that need to addressed after merging this PR? Add them here.
> Update nuget package

- AssetInformationApi.Tests/AssetInformationApi.Tests.csproj
- AssetInformationApi/AssetInformationApi.csproj
Update Asset shared nuget package so patch can be included
> Update Nuget packages

- AssetInformationApi.Tests/AssetInformationApi.Tests.csproj
- AssetInformationApi/AssetInformationApi.csproj
> Add isActive parameter

- .circleci/config.yml
- AssetInformationApi.Tests/AssetInformationApi.Tests.csproj
- AssetInformationApi.Tests/Dockerfile
- AssetInformationApi/AssetInformationApi.csproj
- AssetInformationApi/Dockerfile
- AssetInformationApi/Startup.cs
- AssetInformationApi/build.cmd
- AssetInformationApi/build.sh
- AssetInformationApi/serverless.yml
https://hackney.atlassian.net/browse/MTTL-3267
Update API to .NET 6 as .NET 3.1 is deprecated.
> Upgrade API to .NET 6.0

- AssetInformationApi.Tests/V1/E2ETests/Fixtures/AssetsFixture.cs
- AssetInformationApi.Tests/V1/E2ETests/Steps/AddNewAssetSteps.cs
- AssetInformationApi.Tests/V1/E2ETests/Stories/AddNewAssetTests.cs
- AssetInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- AssetInformationApi/V1/Gateways/DynamoDbGateway.cs
- AssetInformationApi/V1/Infrastructure/Exceptions/DuplicateAssetIdException.cs
> Check for dupe assetId

- AssetInformationApi.Tests/AssetInformationApi.Tests.csproj
- AssetInformationApi/AssetInformationApi.csproj
> Staging release

- AssetInformationApi.Tests/V1/Controllers/AssetInformationApiControllerTests.cs
- AssetInformationApi.Tests/V1/UseCase/AddAssetUseCaseTests.cs
- AssetInformationApi/Startup.cs
- AssetInformationApi/V1/Controllers/AssetInformationApiController.cs
- AssetInformationApi/V1/Gateways/DynamoDbGateway.cs
- AssetInformationApi/V1/UseCase/NewAssetUseCase.cs
Following PR #103 , as the issue is not resolved:
- Added logging (New Asset endpoint - UseCase - Gateway)
> MR-698 - Added logging (New Asset endpoint - UseCase - Gateway)

- AssetInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- AssetInformationApi.Tests/V1/UseCase/AddAssetUseCaseTests.cs
- AssetInformationApi.Tests/V1/UseCase/EditAssetAddressUseCaseTests.cs
- AssetInformationApi.Tests/V1/UseCase/EditAssetUseCaseTests.cs
- AssetInformationApi.Tests/V1/UseCase/GetAssetByAssetIdUseCaseTests.cs
- AssetInformationApi.Tests/V1/UseCase/GetAssetByIdUseCaseTests.cs
- AssetInformationApi/AssetInformationApi.csproj
- AssetInformationApi/Startup.cs
- AssetInformationApi/V1/Gateways/AssetGateway.cs
- AssetInformationApi/V1/Gateways/Interfaces/IAssetGateway.cs
- AssetInformationApi/V1/UseCase/EditAssetAddressUseCase.cs
- AssetInformationApi/V1/UseCase/EditAssetUseCase.cs
- AssetInformationApi/V1/UseCase/GetAssetByAssetIdUseCase.cs
- AssetInformationApi/V1/UseCase/GetAssetByIdUseCase.cs
- AssetInformationApi/V1/UseCase/NewAssetUseCase.cs
Renamed DynamoDbGateway to AssetGateway + tidied up interfaces
> Rename asset gateway

- AssetInformationApi.Tests/AssetInformationApi.Tests.csproj
- AssetInformationApi/AssetInformationApi.csproj
Update AssetShared (boilerHouseId property added to asset table).
> Update asset Shared (add boilerHouseId property)

- AssetInformationApi.Tests/AssetInformationApi.Tests.csproj
- AssetInformationApi/AssetInformationApi.csproj
Updated version of Asset Shared to allow the editing of addresses with no UPRNs
Main feature PR: https://github.com/LBHackney-IT/mtfh-frontend-property/pull/98
> MR-733 - Updated version of Asset Shared to allow the editing of addresses with no UPRNs

- AssetInformationApi.Tests/AssetInformationApi.Tests.csproj
- AssetInformationApi.Tests/V1/Factories/AssetSnsFactoryTests.cs
- AssetInformationApi.Tests/V1/UseCase/AddAssetUseCaseTests.cs
- AssetInformationApi/AssetInformationApi.csproj
- AssetInformationApi/V1/Boundary/Request/AddAssetRequest.cs
- AssetInformationApi/V1/Controllers/AssetInformationApiController.cs
- AssetInformationApi/V1/Factories/AssetSnsFactory.cs
- AssetInformationApi/V1/Factories/ISnsFactory.cs
- AssetInformationApi/V1/Factories/RequestFactory.cs
- AssetInformationApi/V1/Infrastructure/AddRepairsContractsToAssetEventConstants.cs
- AssetInformationApi/V1/Infrastructure/AddRepairsContractsToNewAssetObject.cs
- AssetInformationApi/V1/UseCase/Interfaces/INewAssetUseCase.cs
- AssetInformationApi/V1/UseCase/NewAssetUseCase.cs
[https://hackney.atlassian.net/browse/MR-516?atlOrigin=eyJpIjoiZDU2NzA3ZDA5NjIxNGEzYmI3NWYyMzBlYzY0YmI4MmIiLCJwIjoiaiJ9](https://hackney.atlassian.net/browse/MR-516?atlOrigin=eyJpIjoiZDU2NzA3ZDA5NjIxNGEzYmI3NWYyMzBlYzY0YmI4MmIiLCJwIjoiaiJ9)
When a new asset is created, submit an `AddRepairsContractsToAssetEvent` message. The message is subscribed to by the RepairsListener, which will assign the default contracts to the new asset.
> Staging update

- AssetInformationApi.Tests/AssetInformationApi.Tests.csproj
- AssetInformationApi/AssetInformationApi.csproj
https://hackney.atlassian.net/browse/TS-1131
This is to update the package version as per [this PR](https://github.com/LBHackney-IT/asset-shared/pull/45)
> TS-1131: Update NuGet package to 0.40.0

- AssetInformationApi/V1/Factories/RequestFactory.cs
- AssetInformationApi/V1/Infrastructure/EditAssetDatabase.cs
https://hackney.atlassian.net/browse/TS-1131
As the RentGroup was missing from the object, the API was unable to write into the DB
This PR is to hopefully correct that
> TS-1131: Add RentGroup to EditAssetDatabase

- AssetInformationApi/serverless.yml
Add API gateway logging to help debug adding xray
> Add logging for api gateway

- .circleci/config.yml
- AssetInformationApi/serverless.yml
Configure logging for API gateway. Tested by toggling pipeline
> API gateway logging (attempt 2)

- .circleci/config.yml
- AssetInformationApi/AssetInformationApi.csproj
- AssetInformationApi/Startup.cs
- AssetInformationApi/V1/Middleware/TraceLoggingMiddleware.cs
Log Incoming XRAY TraceID. I was also propted to update SwaggerUI due to a vulnerability.
> Log Incoming XRAY TraceID

- AssetInformationApi/serverless.yml
Serverless config was incorrect
> fix config to enable active tracing in lambda

- AssetInformationApi/V1/Controllers/AssetInformationApiController.cs
Was checking the assetId on the get by assetId endpoint, instead of the ID
> Fix asset restriction

- .gitignore
- AssetInformationApi/V1/Controllers/AssetInformationApiController.cs
- AssetInformationApi/serverless.yml
> Release endpoint restriction exception

- AssetInformationApi/serverless.yml
Update staging lambda authorizer
- Hardcode authorizer ARNs in serverless, preventing any unintended changes via parameter store
- Update staging authorizer to the new version
> Update dev and staging lambda authorizer

- .gitignore
- AssetInformationApi/V1/Controllers/AssetInformationApiController.cs
- AssetInformationApi/serverless.yml
Updated production authorizer ARN
Note: The endpoint restriction is a false diff, this is already on release
> Update production authorizer ARN

- AssetInformationApi.Tests/AssetInformationApi.Tests.csproj
- AssetInformationApi.Tests/V1/Controllers/AssetInformationApiControllerTests.cs
- AssetInformationApi.Tests/V1/E2ETests/Fixtures/AssetsFixture.cs
- AssetInformationApi.Tests/V1/E2ETests/Steps/EditAssetSteps.cs
- AssetInformationApi.Tests/V1/E2ETests/Stories/EditAssetTests.cs
- AssetInformationApi.Tests/V1/E2ETests/Stories/EditPropertyPatchTests.cs
- AssetInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- AssetInformationApi.Tests/V1/UseCase/EditPropertyPatchUseCaseTests.cs
- AssetInformationApi/AssetInformationApi.csproj
- AssetInformationApi/Startup.cs
- AssetInformationApi/V1/Controllers/AssetInformationApiController.cs
- AssetInformationApi/V1/Factories/RequestFactory.cs
- AssetInformationApi/V1/Gateways/AssetGateway.cs
- AssetInformationApi/V1/Infrastructure/EditPropertyPatchDatabase.cs
- AssetInformationApi/V1/UseCase/EditPropertyPatchUseCase.cs
- AssetInformationApi/V1/UseCase/Interfaces/IEditPropertyPatchUseCase.cs
- AssetInformationApi/serverless.yml
> Update patchid areaid endpoint (#167)
